language: python

services:
  - docker

before_install:
  - docker pull fedorapython/fedora-python-tox:latest
  - docker inspect fedorapython/fedora-python-tox:latest
  - docker images

script:
  - docker run --rm -v $PWD:/src -w /src -e TOXENV fedorapython/fedora-python-tox

# Unfortunately, this matrix has to updated manually every time
# we add or remove a tox environment.
matrix:
  include:
  - env: TOXENV=py36,py37,py38,py39,py310,py311,black,mypy
    arch: amd64
  # Arm is slow so we use two separated jobs for it
  - env: TOXENV=py36,py37,py38
    arch: arm64
  - env: TOXENV=py39,py310,py311
    arch: arm64
  - env: TOXENV=py36,py37,py38,py39,py310,py311
    arch: ppc64le
  - env: TOXENV=py36,py37,py38,py39,py310,py311
    arch: s390x
