language: python

services:
  - docker

before_install:
  - docker pull fedorapython/fedora-python-tox
  - docker images

script:
  - docker run --rm -it -v $PWD:/src -w /src -e TOXENV fedorapython/fedora-python-tox

# Unfortunately, this matrix has to updated manually every time
# we add or remove a tox environment.
# To get the list run `tox -l | sed "s/^/  - env: TOXENV=/"`
matrix:
  include:
  - env: TOXENV=py36
  - env: TOXENV=py37
  - env: TOXENV=py38
  - env: TOXENV=py39
